### PR TITLE
Wrap and call redirect() directly

### PR DESCRIPTION
**Pull request by olekenneth**
Because why not?

### CODE REVIEW

**Comment by nelsontky** [comment]
Aitez fair game. That being said someone on HN complained about me using babel probably going the `.then()` route soon.. I didn't know that ES2015 had `then` LOL

**Comment by olekenneth** [comment]
Wow. Quick merge.

**Comment by nelsontky** [comment]
I have never actually reviewed a PR before opps... I just cross my fingers and trust my mates HAHA

**Comment by olekenneth** [comment]
Maybe let you know I'm doing the coding in the Github UI atm.

**Pull request merged**
